winget install -e --id 7zip.7zip
winget install -e --id Kitware.CMake
winget install -e --id Discord.Discord
winget install -e --id JGraph.Draw
winget install -e --id GIMP.GIMP
winget install -e --id Git.Git
winget install -e --id gerardog.gsudo
winget install -e --id Mozilla.Firefox
winget install -e --id Mozilla.Thunderbird
winget install -e --id OBSProject.OBSStudio
winget install -e --id Microsoft.PowerShell
winget install -e --id Microsoft.PowerToys